[workspace]
members = [
    "teaos/aarch64",
    "teaos/boot",
    "teaos/boot-info",
    "teaos/crc",
    "teaos/elf",
    "teaos/kstd",
    "teaos/teaos",
    "xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
