[package]
edition = "2021"
name = "boot"
version = "0.1.0"

[[bin]]
name = "boot"
test = false
harness = false

[dependencies]
cpu = { path = "../cpu" }
crc = { path = "../crc" }
elf = { path = "../elf" }
kstd = { path = "../kstd" }
