[package]
name = "teaos"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "teaos"
test = false
harness = false

[dependencies]
boot = { path = "../boot" }
cpu = { path = "../cpu" }
sync = { path = "../sync" }
