[package]
name = "teaos"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "teaos"
test = false
harness = false

[dependencies]
aarch64 = { path = "../aarch64" }
boot = { path = "../boot" }
kstd = { path = "../kstd" }
